#cloud-config.sandbox.yml
users:
  - name: fiscalismia
    groups: [users, admin]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true

write_files:
  - path: /root/scripts/sandbox_injected_b64.sh
    encoding: b64
    content: ${sandbox_injected_b64}
    permissions: "0755"

runcmd:
  # Initialize logfile
  - export logfile="/root/cloud-config.log"
  - echo "Hello from cloud-config.sandbox.yml!" > $logfile
  - date >> $logfile
  - echo "${ENV_VAR1}" >> $logfile
  - echo "${ENV_VAR2}" >> $logfile
  - /root/scripts/sandbox_injected_b64.sh >> $logfile 2>&1
