volumes:
  database-v:
    name: "database-v"

services:
  # to connect to db in attached docker shell, (RUN apk add --no-cache postgresql-client):
  # psql -U $POSTGRES_USER -d $POSTGRES_DB -h $POSTGRES_HOST -p $POSTGRES_PORT
  # to connect from local machine, the host has to be localhost!
  # psql -U $POSTGRES_USER -d $POSTGRES_DB -h localhost -p $POSTGRES_PORT
  fiscalismia-postgres:
    image: ${POSTGRES_HOST}:1.0.0
    container_name: ${POSTGRES_HOST}
    build:
      context: ./database/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - database-v:/var/lib/postgresql/data
    networks:
      - fiscalismia-network
    command: "-p ${POSTGRES_PORT}"
    # to use healthcheck for backend server see https://wittcode.com/blogs/connect-a-node-server-to-postgres-with-docker-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
    # Container Resource Usage
    deploy:
      resources:
        limits:
          memory: 1536M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # tmpfs for temporary files
    tmpfs:
      - /tmp:noexec,nosuid,size=512m
      - /run:noexec,nosuid,size=512m
    # Security hardening
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
      - DAC_READ_SEARCH # allows reading files regardless of permissions set
    security_opt:
      - no-new-privileges:true

  fiscalismia-backend:
    image: ghcr.io/fiscalismia/fiscalismia-backend-demo:latest
    container_name: fiscalismia-backend
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # The ':z' flag is required on SELinux-enabled systems (like Fedora/CentOS)
      # to relabel the host directory. This allows the container to access the
      # mounted volume by applying a shared SELinux label.
      - /usr/local/etc/fiscalismia-demo/backend/public:/fiscalismia-backend/public:z
      - /etc/letsencrypt/live/demo.fiscalismia.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro,z
      - /etc/letsencrypt/live/demo.fiscalismia.com/privkey.pem:/etc/nginx/certs/privkey.pem:ro,z
    networks:
      - fiscalismia-network
    ports:
      - 8443:8443
    depends_on:
      fiscalismia-postgres:
        condition: service_healthy
    # Container Resource Usage
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.6'
        reservations:
          memory: 512M
          cpus: '0.4'
    # Capabilities (minimal required permissions)
    cap_drop:
      - ALL
    # cap_add:
      # - CAP_DAC_READ_SEARCH # Bypass file read permission checks and directory read and execute permission checks
    security_opt:
      - no-new-privileges:true

  fiscalismia-frontend:
    image: ghcr.io/fiscalismia/fiscalismia-frontend-demo:latest
    container_name: fiscalismia-frontend
    pull_policy: always
    restart: unless-stopped
    volumes:
      # The ':z' flag is required on SELinux-enabled systems (like Fedora/CentOS)
      # to relabel the host directory. This allows the container to access the
      # mounted volume by applying a shared SELinux label.
      - /etc/letsencrypt/live/demo.fiscalismia.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:z
      - /etc/letsencrypt/live/demo.fiscalismia.com/privkey.pem:/etc/nginx/certs/privkey.pem:z
    ports:
      - 443:443
    # Container Resource Usage
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
        reservations:
          memory: 256M
          cpus: '0.2'
    ### SECURITY HARDENING (minimal required permissions)
    tmpfs:
      - /tmp:noexec,nosuid,size=256m
      - /var/cache/nginx:noexec,nosuid,size=128m
      - /var/run:noexec,nosuid,size=64m
    cap_drop:
      - ALL
    cap_add:
      # if binding to ports < 1024 also requires the following setting on the host:
      # echo "net.ipv4.ip_unprivileged_port_start=80" | sudo tee /etc/sysctl.d/nonroot_can_bind_to_low_ports.conf
      - NET_BIND_SERVICE
      # - CAP_DAC_OVERRIDE # Bypass file read, write, and execute permission checks.
    security_opt:
      - no-new-privileges:true

networks:
  fiscalismia-network:
    name: fiscalismia-network
    driver: bridge