- name: Install python dependencies for caller_info command
  ansible.builtin.dnf:
    name:
      - python3-pip
      - python3-boto3
      - python3-packaging
      - python3-requests
    state: latest
    update_cache: true

