- name: Log in to Development Repository
  community.docker.docker_login:
    registry_url: "{{ docker_repository }}"
    # validate_certs: false
    # tls: false
    debug: yes
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    reauthorize: yes
  register: login_output
- debug: msg={{ login_output.login_result }}